package thai.dev.data.model;

public class User {

    private int id;
    private String email;
    private String password;
    private String role;
    private String confirmationCode; // New field for confirmation code
    private boolean isConfirmed; // New field to track confirmation status

    // Constructor for new users (without ID)
    public User(String email, String password, String role, String confirmationCode, boolean isConfirmed) {
        this.email = email;
        this.password = password;
        this.role = role;
        this.confirmationCode = confirmationCode;
        this.isConfirmed = isConfirmed;
    }

    // Constructor with ID
    public User(int id, String email, String password, String role, String confirmationCode, boolean isConfirmed) {
        this.id = id;
        this.email = email;
        this.password = password;
        this.role = role;
        this.confirmationCode = confirmationCode;
        this.isConfirmed = isConfirmed;
    }

    // Constructor without confirmation code (for existing users)
    public User(int id, String email, String password, String role) {
        this.id = id;
        this.email = email;
        this.password = password;
        this.role = role;
    }

    public User(String email, String autoGeneratedPassword, String user) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Getters and setters for new fields
    public String getConfirmationCode() {
        return confirmationCode;
    }

    public void setConfirmationCode(String confirmationCode) {
        this.confirmationCode = confirmationCode;
    }

    public boolean isConfirmed() {
        return isConfirmed;
    }

    public void setConfirmed(boolean confirmed) {
        isConfirmed = confirmed;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }
}
